DocumentViewId can usually be a string
p2panda/shirokuma pull request #29
Opened 2023-11-13 07:03 UTC by jadehopepunk

`DocumentViewId` was defined as `string | string[]`. This makes life really hard because it's the return value from P2Panda creates and updates, you need to constantly check to see if it's actually an array. This seemed to be needed because in nextArgs, we genuinely did want an array of document view ids. Further complicating that, however, that array was sent over the wire in graphql by joining the ids with underscores and making it a string.

In p2panda-js there's a function encodeOperation which handles operation.previous being either a string or an array, and splits it by underscore if it's a string. I think that's the only place we need this functionality. I also think that's a bad idea. I don't see a corresponding join anywhere in the p2panda-js codebase, and there wasn't one in Shirokuma either. To try and be correct, I've added one, but I really dislike this as the join and split are in two seperate codebases, and this transmission standard isn't written anywhere.

Anyway, can anyone tell me if this change is correct? If we can merge it into shirokuma, my app code can have a much easier time handling the returned ids and not needing to check if they might be arrays.

## 📋 Checklist

- [ ] Add tests that cover your changes
- [ ] Add this PR to the _Unreleased_ section in `CHANGELOG.md`
- [ ] Link this PR to any issues it closes
- [ ] New files contain a SPDX license header

2023-11-13 10:19 UTC, adzialocha requested changes
Thank you @jadehopepunk! This totally makes sense from a high-level GraphQL perspective, it is indeed confusing. However the types are a bit off now when it comes to the core p2panda definitions and the doc strings. Since `p2panda-js` is a core library we should make sure that this is correctly representing the specification in both doc strings and type definitions.

A "document view id" is an array of "operation ids" (https://p2panda.org/specification/data-types/document-views#document-view-id), multiple "document view ids" we would usually only see in a pinned relation list (https://p2panda.org/specification/data-types/schemas#relation-fields). The "joining" only exists because of GraphQL.

Anyhow, without digging too deep into the specification for now as this PR is about DX I'd suggest you reverse all changes and doc-strings to how they were and introduce a new type named `DocumentViewIdString` / `JoinedDocumentViewId` or use simply just `string` directly in place where you need it in the method?

2023-11-14 08:29 UTC, jadehopepunk commented
@adzialocha I've done that now, what do you think? At the moment, `DocumentViewIdString` is used as the return promise from create and update, which is the particular problem I had. However, I'm unsure about where it's used in `NextArgs`, or as the previous field. Seems like those should be DocumentViewIdStrings too, but maybe people are sometimes using arrays of operation ids instead?

2023-11-15 21:18 UTC, adzialocha commented
> @adzialocha I've done that now, what do you think?

Great! This looks good now! Thank you!

> At the moment, `DocumentViewIdString` is used as the return promise from create and update, which is the particular problem I had. However, I'm unsure about where it's used in `NextArgs`, or as the previous field. Seems like those should be DocumentViewIdStrings too, but maybe people are sometimes using arrays of operation ids instead?

Good point, technically speaking the `nextArgs` GraphQL request takes `viewId` as an argument, which from a p2panda-spec perspective is a document view id aka, again an array of operation IDs. Since that's hard to model in GraphQL we should have also checked here in the code if we got an array and then transform it into that underscore string representation before sending it. I'd be fine with just _not_ doing that though and also using `DocumentViewIdString`, it seems more like how developers would interact with this API. Same with `previous`!

How about this mix of both worlds:

1. Remove `DocumentViewIdString` again
2. Make `DocumentViewId` a string
3. Not change the doc string but just mention that here we represent it always as a string with underscores between the operation ids
4. Remove the array to string conversion

There are other places as well in the doc strings where arrays are mentioned btw, that would need changing as well.

2023-11-20 05:37 UTC, jadehopepunk commented
I agree, and I've made that change in this PR now, but it's got failures in `session.test.ts` that I'm not sure about. It seems to be expecting an array for `previous`

2025-08-01 03:25 UTC, closed without merging